# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/instrument_performance',
                'doc_host': 'https://Sean-RF.github.io',
                'git_url': 'https://github.com/Sean-RF/instrument_performance',
                'lib_path': 'instrument_performance'},
  'syms': { 'instrument_performance.performance_study': { 'instrument_performance.performance_study.Instrument': ( 'core.html#instrument',
                                                                                                                   'instrument_performance/performance_study.py'),
                                                          'instrument_performance.performance_study.Instrument.__init__': ( 'core.html#instrument.__init__',
                                                                                                                            'instrument_performance/performance_study.py'),
                                                          'instrument_performance.performance_study.Instrument.amethod': ( 'core.html#instrument.amethod',
                                                                                                                           'instrument_performance/performance_study.py'),
                                                          'instrument_performance.performance_study.Instrument.anothermethod': ( 'core.html#instrument.anothermethod',
                                                                                                                                 'instrument_performance/performance_study.py')}}}
