# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/instrument_performance',
                'doc_host': 'https://Sean-RF.github.io',
                'git_url': 'https://github.com/Sean-RF/instrument_performance',
                'lib_path': 'instrument_performance'},
  'syms': {'instrument_performance.core': {'instrument_performance.core.foo': ('core.html#foo', 'instrument_performance/core.py')}}}
