"""Compute performance metrics of an instrument based on design constraints"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['Instrument']

# %% ../nbs/00_core.ipynb 5
class Instrument:
    "An instance of an instrument to be studied."
    def __init__(self):
        self.altitude = None #geodetic orbital altitude in m, specified over equatorial radius
        self.scan_angle_limit = None #


    def amethod(self): #hello you can hear me
        "stuff will be computed"
        return altitude*3
    
    def anothermethod(self,x:float = 0 # x has special qualities
                      ):
        return x + 10
